//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DedDom
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class heroku_b27ae8c6ecb20b8Entities : DbContext
    {
        public heroku_b27ae8c6ecb20b8Entities()
            : base("name=heroku_b27ae8c6ecb20b8Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<@class> classes { get; set; }
        public virtual DbSet<classrom> classroms { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<schedule> schedules { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<subject> subjects { get; set; }
        public virtual DbSet<teacher> teachers { get; set; }
        public virtual DbSet<visit> visits { get; set; }
        public virtual DbSet<visit_log> visit_log { get; set; }
        public virtual DbSet<week_day> week_day { get; set; }
    }
}
