//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DedDom
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public schedule()
        {
            this.visit_log = new HashSet<visit_log>();
        }
    
        public int Id { get; set; }
        public int Id_Subject { get; set; }
        public Nullable<System.TimeSpan> Start_Time { get; set; }
        public Nullable<System.TimeSpan> End_Time { get; set; }
        public int Id_Group { get; set; }
        public int Id_Classroom { get; set; }
        public int Id_Week_Day { get; set; }
        public Nullable<bool> IsActual { get; set; }
    
        public virtual classrom classrom { get; set; }
        public virtual group group { get; set; }
        public virtual subject subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visit_log> visit_log { get; set; }
        public virtual week_day week_day { get; set; }
    }
}
