//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DedDom
{
    using System;
    using System.Collections.Generic;
    
    public partial class visit_log
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public visit_log()
        {
            this.visits = new HashSet<visit>();
        }
    
        public int Id { get; set; }
        public int Id_Schedule { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Id_Teacher { get; set; }
    
        public virtual schedule schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visit> visits { get; set; }
        public virtual teacher teacher { get; set; }
    }
}
