//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DedDom
{
    using System;
    using System.Collections.Generic;
    
    public partial class visit
    {
        public int id_visit { get; set; }
        public int Id_student { get; set; }
        public int Id_visit_log { get; set; }
        public Nullable<bool> isPresent { get; set; }
    
        public virtual student student { get; set; }
        public virtual visit_log visit_log { get; set; }
    }
}
