//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DedDom
{
    using System;
    using System.Collections.Generic;
    
    public partial class visit
    {
        public int id_visit { get; set; }
        public int Id_student { get; set; }
        public int Id_visit_log { get; set; }
        public Nullable<bool> isPresent { get; set; }
    
        public virtual student student { get; set; }
        public virtual visit_log visit_log { get; set; }
    }
}
